openapi: 3.0.3
tags:
  - ""
summary: "Upload a PDF file"
description: "This route allows the user to upload a pdf file and return the entities detected in this file"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid Order"
            