openapi: 3.0.3
tags:
  - "get entities from batch"
summary: "Return all the entities found inside a batch of [1;5] papers"
description: "This route allows the user to use this entrypoint as a post request. This entrypoint return all the entities found inside the links puts as inputs"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
      - name: "linkof papers"
        in: "body"        
        description: "http link"
        schema:
            type: object
            properties:
            
responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid Order"
            